name: Lint job board frontend on PR

on:
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  check-style:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3


      - name: Install dependencies and run linter
        working-directory: ./frontend/job_board_frontend
        run: |
          npm install
          npm run lint
